stages:
  - build
  - test
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  
unit_tests:
  stage: test
  image: fontolan/webserver:latest
  
smoke_tests:
  stage: test
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - echo "Running smoke tests"
    - sleep 60  
    - curl -f http://webserver.default.svc.cluster.local || (echo "Smoke tests failed" && exit 1)

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - echo "$KUBECONFIG" > kubeconfig
    - export KUBECONFIG=$(pwd)/kubeconfig
    - kubectl config use-context $KUBE_CONTEXT
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
  environment:
    name: webserver
    url: http://your-production-url.com


    
