apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: default
spec:
  selector:
    app: webserver
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: ClusterIP
status:
  loadBalancer: {}
